version: '3.8'
services:
  portal1:
    image: registry.cn-hangzhou.aliyuncs.com/sparta/sparta-portal:0.0.1-SNAPSHOT
    ports:
      - 8080
    environment:
      SHARD_ID: 1
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Shanghai


