version: '3.8'

services:
  user:
    container_name: user
    build:
      context: ../../sparta-user
    external_links:
      - consul
      - mysql
      - redis
    ports:
      - 8080
    environment:
      SHARD_ID: 1
      SPRING_PROFILES_ACTIVE: dev
      TZ: Asia/Shanghai
